# -*- coding: utf-8 -*-
# Copyright 2025-2026, Antonio Alvarado <tnotstar@gmail.com>

[settings]
default_target_type = "automatic"

[helpers]

[nushell.files]
"etc/nushell/config.nu" = "~/.config/nushell/config.nu"

[starship.files]
"etc/starship/starship.template" = "~/.config/starship.toml"

[starship.variables]
starship_package_disabled = false
starship_git_branch_disabled = false
starship_git_commit_disabled = false

[git.files]
"etc/git/gitconfig.template" = "~/.gitconfig"

[git.variables]
git_core_ssh_command = "ssh"
git_gpg_ssh_program = "ssh-keygen"

[nvim.files]
"etc/nvim/init.lua" = "~/.config/nvim/init.lua"

[vscode.files]
"etc/vscode/user-settings.json" = "~/.config/Code/User/settings.json"

[mamba.files]
"etc/mamba/mambarc" = "~/.mambarc"

[default]
depends = ["nushell", "starship", "git", "nvim", "vscode", "mamba"]
